api_key: 'key-32b1722087d9bfe0e1706abca30f4490'
domain: 'alexandermaru.com'
username: 'postmaster@alexandermaru.com'
password: 'f05b141c78c37d511eb232acbaf38ad6'
gmail_username: 'marua7665@gmail.com'
gmail_password: '@#{hps,gml,COM}.8136'